# Perfil de PRODUCCION - PostgreSQL en Render
# Render inyecta DATABASE_URL (jdbc:postgresql://usuario:pass@host:puerto/db)
spring.datasource.url=${DATABASE_URL}
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false# Perfil de PRODUCCION - PostgreSQL en Render
# Render inyecta DATABASE_URL (jdbc:postgresql://usuario:pass@host:puerto/db)
spring.datasource.url=${DATABASE_URL}
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false